name: "vprofile-IAC"
on:
  push:
    branches:
       - main
       - stage
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_DEFAULT_REGION: us-east-1  

  EKS_CLUSTER_NAME: vpro-ekss

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
       run: 
        shell: bash
        working-directory: ./terraform
    steps:
      
      - name: Apply terrform code changes
        uses: actions/checkout@v4
      
      - name: setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
           terraform-version: 1.6.3

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE" 
      
      - name: Terraform format 
        id: fmt
        run: terraform fmt -check 

      - name: Terraform validate
        id: validate
        run: terraform validate  

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true
      
      - name: terraform plan status 
        if: ${{ steps.plan.conclusion == 'failure' }}
        run: exit 1

      - name: Terraform apply
        run: terraform apply planfile
     